# Generated by Django 4.1.5 on 2023-02-23 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0001_initial'),
        ('App_UserLog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userlog',
            name='object_id',
        ),
        migrations.AddField(
            model_name='userlog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Shop.product'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(max_length=100),
        ),
    ]
