# Generated by Django 4.1.5 on 2023-02-23 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_UserLog', '0003_alter_userlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='product',
        ),
        migrations.AddField(
            model_name='userlog',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='userlog',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
