# Generated by Django 4.1.5 on 2023-02-23 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_UserLog', '0004_remove_userlog_product_userlog_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlog', to=settings.AUTH_USER_MODEL),
        ),
    ]
