# Generated by Django 4.1.5 on 2023-02-27 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('App_UserLog', '0008_alter_userlog_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
