# Generated by Django 4.1.5 on 2023-02-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserLog', '0009_alter_userlog_content_type'),
    ]

    operations = [
    ]
