# Generated by Django 4.1.5 on 2023-02-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserLog', '0010_add_default_value_to_content_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
