# Generated by Django 4.1.5 on 2023-02-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserLog', '0012_alter_userlog_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
